### PR TITLE
Add GearBot to bot list

### PR DESCRIPTION
**Pull request by aejb**
This PR adds [GearBot](https://gearbot.rocks) to the list of recommended bots. This is a widely used moderation bot, used by many official Discord servers, and comes with a wide array of manual and automatic moderation tools.

### CODE REVIEW

**Review by XynoxTheDev — CHANGES_REQUESTED** [review]
There are many bots that are more or less, I would like to suggest a bot that is multipurpose and would do the work of most of the bots.
- All-purpose: [Skyra](http://skyra.pw/)
- In place of the ticket tool, one could host their own Modmail for free from [here](https://github.com/kyb3r/modmail).
> I hope my suggestions are good enough to be approved other no worries, thank you!

**Comment by aejb** [comment]
> * All-purpose: [Skyra](http://skyra.pw/)

I admittedly don't have much experience with Skyra, my recommendation of GearBot comes from it being widely used and supported by official Discord servers. Does Skyra provide features GearBot does not?

> * In place of the ticket tool, one could host their own Modmail for free from [here](https://github.com/kyb3r/modmail).

While I do like Kyb3r's Modmail, it requires self-hosting, which is a bit of a steep learning-curve for first-time Discord users. It could be recommended as an alternative for people comfortable with Discord's Bot API?ou!

**Comment by XynoxTheDev** [comment]
> I admittedly don't have much experience with Skyra, my recommendation of GearBot comes from it is widely used and supported by official Discord servers. Does Skyra provide features GearBot does not?

Skyra has a lot of features also there are many commands/features which are way better than GearBot, GearBot is widely used for moderation purpose across Discord (by Discord itself). But Skyra has different modules like reaction roles, moderation, music(which can be used to play audio files), announcements, and [more](https://skyra.pw/commands). When you have all in one bot then why go for 10 other bots!

> While I do like Kyb3r's Modmail, it requires self-hosting, which is a bit of a steep learning-curve for first-time Discord users. It could be recommended as an alternative for people comfortable with Discord's Bot API?

They can easily do it as mentioned in their Github's `README` and I guess a person without knowledge can also host using Heroku. If this can be a drawback then we can also attach a video created from our side for help or there are many Youtube tutorials for it to explain the setup as well as working very well.

**Comment by juanpflores** [comment]
> > I admittedly don't have much experience with Skyra, my recommendation of GearBot comes from it is widely used and supported by official Discord servers. Does Skyra provide features GearBot does not?
> 
> Skyra has a lot of features also there are many commands/features which are way better than GearBot, GearBot is widely used for moderation purpose across Discord (by Discord itself). But Skyra has different modules like reaction roles, moderation, music(which can be used to play audio files), announcements, and [more](https://skyra.pw/commands). When you have all in one bot then why go for 10 other bots!
> 
> > While I do like Kyb3r's Modmail, it requires self-hosting, which is a bit of a steep learning-curve for first-time Discord users. It could be recommended as an alternative for people comfortable with Discord's Bot API?
> 
> They can easily do it as mentioned in their Github's `README` and I guess a person without knowledge can also host using Heroku. If this can be a drawback then we can also attach a video created from our side for help or there are many Youtube tutorials for it to explain the setup as well as working very well.

This is a great discussion! Feel free to open a PR to add more bots to the list if you feel it would be a great tool.

**Review by juanpflores — APPROVED** [review]

**Pull request merged**
